### ISSUE TITLE
#1 How to implement event-streaming in Restful API.

### ISSUE THREAD

**Issue by SmartDev222** [SmartDev222/WPF-Control#1]
I have tried to implement the event-streaming in Restful API several times. And of course,  I was managed to get the result.
But I wanna know about that exact code for that. thx

**Comment by devman0207** [comment]
Hi @SmartDev222 

Here is sourecode.
// frontend side
await fetchEventSource("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          question,
          history,
          filter,
          ip: localStorage.getItem("ip"),
        }),
        signal: ctrl.signal,
        openWhenHidden: true,
        onmessage: (event) => {
          clearTimeout(timeoutId);
          if (event.data === "[NEEDPRENIUM]") {
            NotificationManager.warning(
              "Please upgrade your plan.",
              "Notification",
              2000
            );
            ctrl.abort();
          }
          if (event.data === "[DONE]") {
            setMessageState((state: any) => ({
              history: [
                ...state.history,
                [{ role: "user", content: question }],
                [{ role: "assistant", content: state.pending ?? "" }],
              ],
              messages: [
                ...state.messages,
                {
                  type: "apiMessage",
                  message: state.pending ?? "",
                  sourceDocs: state.pendingSourceDocs,
                },
              ],
              pending: undefined,
              pendingSourceDocs: undefined,
            }));
            setLoading(false);
            setFormating(false);
            ctrl.abort();
          } else {
            if (event.data === "[FORMATING]") {
              setFormating(true);
            } else {
              const data = JSON.parse(event.data);
              if (data.sourceDocs) {
                setMessageState((state) => ({
                  ...state,
                  pendingSourceDocs: data.sourceDocs,
                }));
              } else {
                setMessageState((state) => ({
                  ...state,
                  pending: (state.pending ?? "") + data.data,
                }));
              }
            }
          }
        },
      });

//Backend

 res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
    "X-Accel-Buffering": "no",
  });
  
  
 It works well.
 Hope everything goes well.

**Comment by devman0207** [comment]
It is same as fetchEventSource.

The main point write header before send response.

here
res.writeHead(200, {
"Content-Type": "text/event-stream",
"Cache-Control": "no-cache, no-transform",
Connection: "keep-alive",
"X-Accel-Buffering": "no",
});
